Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieDatabase.Data;
using MovieDatabase.Models;
using MovieDatabase.ViewModels;

namespace MovieDatabase.Controllers
{
    public class MoviesController : FilmController
    {
        /**
         * Controller class for movie
         */

        public MoviesController(MovieContext context) : base(context)
        {
            
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            List<Film> films = await _context.Films.Select(m => m).ToListAsync();
            foreach (Film film in films)
            {
                film.AverageRate = await CalculateAverageRatio(film);
            }

            return View(films);
        }
        [HttpPost]
        public async Task<IActionResult> Index(string filmName)
        {
            var items = await _context.Films.Select(m => m).Where(m => m.Title.Contains(filmName)).ToListAsync().ConfigureAwait(false);
            foreach(Film film in items)
            {
                film.AverageRate = await CalculateAverageRatio(film);
            }
            return View(items);
        }

       [Authorize]
        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateMovie(/*[Bind("Id,Title,Length,Director,ReleaseDate,Description,Rating,Genre")]*/ Movie movie)
        {
            return await base.CreateFilm(movie);
        }

        // GET: Movies/Edit/5
        [Authorize]
        new public async Task<IActionResult> Edit(int id)
        {
            return await base.Edit(id);
            
        }
        public async Task<IActionResult> ListAllMoviesForGenre(int id)
        {
            Genre genre = await _context.Genres.FindAsync(id);
            
            if(genre == null)
            {
                return NotFound();
            }
            List<Film> listWithFilms =await  _context.Genres
                .Where(g=>  g.Name.Equals(genre.Name))
                .Select(i => i.Film).ToListAsync().ConfigureAwait(false);
            List<Film> listWithFilmsDirectors = new List<Film>();
            GenreAndMoviesViewModel viewModel = new GenreAndMoviesViewModel
            {
                MovieGenrie = genre,
                Movies = listWithFilms
            };
            return View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> ListAllMoviesForStar(int id)
        {
            Role star = await _context.Stars.FindAsync(id);
            if (star == null)
            {
                return NotFound();
            }
            List<Film> listWithFilmsForStar = await _context.Stars
                .Where(s => s.FirstName.Equals(star.FirstName) && s.LastName.Equals(star.LastName) && s.Birthday.Equals(star.Birthday))
                .Select(s => s.Film)
                .ToListAsync();

            RoleAndMoviesViewModel roleAndMoviesViewModel = new RoleAndMoviesViewModel
            {
                MovieRole = star,
                Movies = listWithFilmsForStar
            };
            return View("ListAllMoviesForRole", roleAndMoviesViewModel);
        }
        [Authorize]
        public async Task<IActionResult> RateFilm(int id)
        {
            Film film = await _context.Films.FindAsync(id);
            if(film == null)
            {
                return NotFound();
            }
            return View(film);
        }
        [Authorize]
        [HttpPost]
        public  async Task<IActionResult> SubmitRating(Movie film)
        {
          return await  base.SubmitRatingAsync(film).ConfigureAwait(false);
        }

        public IActionResult AddMovie()
        {
            return View();
        }

        public async Task<IActionResult> ShowMovieDetails(int id)
        {
            return await base.ShowMovieDetail(id).ConfigureAwait(false);
           
        }


        public async Task<IActionResult> ListAllMoviesForDirector(int id)
        {
            Role director = await _context.Director.FindAsync(id);
            if (director == null)
            {
                return NotFound();
            }
            List<Film> listWithFilmsForStar = await _context.Director
                .Where(d => d.FirstName.Equals(director.FirstName) && d.LastName.Equals(director.LastName) && d.Birthday.Equals(director.Birthday))
                .Select(s => s.Film)
                .ToListAsync();

            RoleAndMoviesViewModel roleAndMoviesViewModel = new RoleAndMoviesViewModel
            {
                MovieRole = director,
                Movies = listWithFilmsForStar
            };
            return View("ListAllMoviesForRole", roleAndMoviesViewModel);
        }

        //Show all movies and tv shown in database
        public async Task<IActionResult> MoviesAndTvShown()
        {
            List<Film> allFilms = await _context.Films.Select(m => m).Include(C => C.Director).Include(c =>c.Genres).Include(c=>c.Stars).Include(C=>C.User).ToListAsync().ConfigureAwait(false);
            //do not show duplicates e.g same film created or rated by more than one user
            HashSet<Film> films = new HashSet<Film>(allFilms);
            List<Movie> movies = films.OfType<Movie>().ToList();
            List<TvShow> tvShows = films.OfType<TvShow>().ToList();
            FilmViewModel filmViewModel = new FilmViewModel() { Movies = movies, TvShows = tvShows };
            return View(filmViewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> EditMovieDone(Movie movie)
        {
           return await base.EditMovieDoneAsync(movie).ConfigureAwait(false);
        }
    }
}

Controllers/TvShowController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieDatabase.Data;
using MovieDatabase.Models;

namespace MovieDatabase.Controllers
{
    /**
     * Controller class for tv show
     */
    public class TvShowController : FilmController
    {

        public TvShowController(MovieContext context) : base(context) { }
      

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }
        public async Task<IActionResult> CreateTvShow(/*[Bind("Id,Title,Length,Director,ReleaseDate,Description,Rating,Genre")]*/ TvShow movie)
        {
            return await base.CreateFilm(movie);
        }



        [Authorize]
        new public async Task<IActionResult> Edit(int id)
        {
            return await base.Edit(id);            
        }
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> EditMovieDone(TvShow movie)
        {
            return await base.EditMovieDoneAsync(movie);
        }


        public async Task<IActionResult> ShowMovieDetails(int id)
        {
            return await base.ShowMovieDetail(id);

        }
    }
}

Views/Movies/Create.cshtml
@model MovieDatabase.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateMovie">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Length" class="control-label"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YoutubePreviewLink" class="control-label"></label>
                <input asp-for="YoutubePreviewLink" class="form-control" />
                <span asp-validation-for="YoutubePreviewLink" class="text-danger"></span>
            </div>
            <p>Add director</p>
            <div class="form-group">

                <table id="myRows" class="table">
                    <tr class="myrow">
                        <td class="section table-column-center">
                            <label asp-for="Director.FirstName" class="control-label"></label>
                            <input asp-for="Director.FirstName" type="text" class="span4 input-large search-query" />
                            <span asp-validation-for="Director.FirstName" class="text-danger"></span>
                        </td>
                        <td class="section table-column-center">
                            <label asp-for="Director.LastName" class="control-label"></label>
                            <input asp-for="Director.LastName" type="text" class="span4 input-large search-query" />
                            <span asp-validation-for="Director.LastName" class="text-danger"></span>
                        </td>
                        <td class="section table-column-center">
                            <label asp-for="Director.FilePath" class="control-label"></label>
                            <input asp-for="Director.FilePath" type="file" class="span4 input-large search-query" />
                            <span asp-validation-for="Director.FilePath" class="text-danger"></span>
                        </td>

                        <td class="section table-column-center">
                            <label asp-for="Director.Birthday" class="control-label"></label>
                            <input asp-for="Director.Birthday" class="span4 input-large search-query" />
                            <span asp-validation-for="Director.Birthday" class="text-danger"></span>
                        </td>
                    </tr>
                </table>
            </div>
            <p> Add Genre</p>
            <div class="form-group">

                <table id="myGenreRows" class="table">
                    <tr class="mygenrerow">
                        <td class="section table-column-center">
                            <label asp-for="Genres[0].Name" class="control-label"></label>
                            <input asp-for="Genres[0].Name" class="form-control" />
                            <span asp-validation-for="Genres[0].Name" class="text-danger"></span>
                        </td>
                    </tr>

                </table>
            </div>

            <div class="item-add-genre">
                <a id="add-genre-row" class="btn btn-outline-secondary">Add more genres</a>
            </div>
            <br />
            <br />
            <p>Add actors</p>
            <div class="form-group">

                <table id="myArtistRows" class="table">
                    <tr class="myartistrow">
                        <td class="section table-column-center">
                            <label asp-for="Stars[0].FirstName" class="control-label"></label>
                            <input asp-for="Stars[0].FirstName" type="text" class="span4 input-large search-query" />
                            <span asp-validation-for="Stars[0].FirstName" class="text-danger"></span>
                        </td>
                        <td class="section table-column-center">
                            <label asp-for="Stars[0].LastName" class="control-label"></label>
                            <input asp-for="Stars[0].LastName" class="span4 input-large search-query" />
                            <span asp-validation-for="Stars[0].LastName" class="text-danger"></span>
                        </td>
                        <td class="section table-column-center">
                            <label asp-for="Stars[0].FilePath" class="control-label"></label>
                            <input asp-for="Stars[0].FilePath" type="file" class="span4 input-large search-query" />
                            <span asp-validation-for="Stars[0].FilePath" class="text-danger"></span>
                        </td>

                        <td class="section table-column-center">
                            <label asp-for="Stars[0].Birthday" class="control-label"></label>
                            <input asp-for="Stars[0].Birthday" type="date" class="input-large search-query" />
                            <span asp-validation-for="Stars[0].Birthday" class="text-danger"></span>
                        </td>
                    </tr>

                </table>
            </div>



            <div class="item-add-artist">
                <a id="add-row-artist" class="btn btn-outline-secondary">Add more artists</a>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts
    {
    <script>
        $("#add-row-artist").click(function () {
            var nextId = $(".myartistrow").length;

            var rowHtml = '<tr class="myartistrow">' +
            '<td class="section table-column-center" >' +
            '<input class="span4 input-large search-query" type="text" id="Stars_' + nextId + '_FirstName" name="Stars[' + nextId + '].FirstName" value=""/>' +

            '<span class="text-danger field-validation-valid" data-valmsg-for="Stars[' + nextId + '].Stars" data-valmsg-replace="true"></span>' +

            '</td>' +

            '<td class="section table-column-center">' +
            '<input class="span4 input-large search-query" type="text" id="Stars_' + nextId + '_LastName" name="Stars[' + nextId + '].LastName" value=""/>' +

            '<span class="text-danger field-validation-valid" data-valmsg-for="Stars[' + nextId + '].LastName" data-valmsg-replace="false"></span>' +

            '</td>' +
            '<td class="section table-column-center">' +
                '<input class="span4 input-large search-query" type="file" id="Stars_' + nextId + '_FilePath" name="Stars[' + nextId + '].FilePath" value=""/>' +

                '<span class="text-danger field-validation-valid" data-valmsg-for="Stars[' + nextId + '].FilePath" data-valmsg-replace="true"></span>' +

            '</td>' +

                '<td class="section table-column-center">' +
                 '<input  type="date" id="Stars_' + nextId + '_Image" name="Stars[' + nextId + '].Birthday" value=""/>' +
                '<span class="data-provide="datepicker" data-valmsg-for="Stars[' + nextId + '].Birthday" data-valmsg-replace="true"></span>' +
        
            '</td>' +

            '</tr>';

            $("#myArtistRows").append(rowHtml);
        });
        $("#add-genre-row").click(function () {
            var nextId = $(".mygenrerow").length;

            var rowHtml = '<tr class="mygenrerow">' +
                '<td class="section table-column-center" >' +
                '<input class="form-control" type="text" id="Genres_' + nextId + '_Name" name="Genres[' + nextId + '].Name" value=""/>' +

                '<span class="text-danger field-validation-valid" data-valmsg-for="Genres[' + nextId + '].Name" data-valmsg-replace="true"></span>' +

                '</td>' +

                '</tr>';

            $("#myGenreRows").append(rowHtml);
        });
    </script>
}

Views/Movies/Edit.cshtml
@model MovieDatabase.Models.Movie

@{
    ViewData["Title"] = "EditMovie";
}

<h1>EditMovie</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditMovieDone">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FilmId" />
            <input type="hidden" asp-for="User" />
            <input type="hidden" asp-for="Image" />

            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Length" class="control-label"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilePath" class="control-label"></label>
                <input asp-for="FilePath" class="form-control" />
                <span asp-validation-for="FilePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YoutubePreviewLink" class="control-label"></label>
                <input asp-for="YoutubePreviewLink" class="form-control" />
                <span asp-validation-for="YoutubePreviewLink" class="text-danger"></span>
            </div>

            <div class="col-xs-4">
                <label asp-for="Director.FirstName" class="control-label"></label>
                <input asp-for="Director.FirstName" class="form-control" />
                <span asp-validation-for="Director.FirstName" class="text-danger"></span>

                <label asp-for="Director.LastName" class="control-label"></label>
                <input asp-for="Director.LastName" class="form-control" />
                <span asp-validation-for="Director.LastName" class="text-danger"></span>

                <label asp-for="Director.Birthday" class="control-label"></label>
                <input asp-for="Director.Birthday" class="form-control" />
                <span asp-validation-for="Director.Birthday" class="text-danger"></span>
            </div>

            <div class="col-xs-4">
                @{
                    var stars = Model.Stars;
                    <p>Participating stars</p>
                    for (int i = 0; i < stars.Count; i++)
                    {
                        <text>
                            <div>
                                <label asp-for="@stars[@i].StarId" class="control-label"></label>
                                <input type="hidden" name="stars[@i].StarId" value="@stars[i].StarId" readonly="readonly" />
                            </div>
                            <div>
                                <label asp-for="@stars[@i].FirstName" class="control-label"></label>
                                <input type="text" name="stars[@i].FirstName" value="@stars[i].FirstName" />
                            </div>
                            <div>
                                <label asp-for="@stars[@i].LastName" class="control-label"></label>
                                <input type="text" name="stars[@i].LastName" value="@stars[i].LastName" />
                            </div>
                            <div>
                                <label asp-for="@stars[@i].Birthday" class="control-label"></label>
                                <input type="text" name="stars[@i].Birthday" value="@stars[i].Birthday" />
                            </div>
                        </text>
                    }
                }
            </div>

            <div class="col-xs-4">
                @{
                    var genres = Model.Genres;
                    <p>Genres</p>
                    for (int j = 0; j < genres.Count; j++)
                    {
                        <text>
                            <div>
                                <label asp-for="@genres[@j].GenreId class=" control-label"></label>
                                <input type="text" name="genres[@j].GenreId" value="@genres[j].GenreId " readonly="readonly" />
                            </div>
                            <div>
                                <label asp-for="@genres[@j].Name" class="control-label"></label>
                                <input type="text" name="genres[@j].Name" value="@genres[j].Name" />
                            </div>
                        </text>
                    }
                }
            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Movies/Index.cshtml
@model IEnumerable<MovieDatabase.Models.Film>
@{
    Layout = null;
}
@{
    ViewData["Title"] = "Movie data webpage and database";
}
<link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
<div>
    <p>
        Hello from movie index method
    </p>
    <div class="panel-body">
        <table class="table table-bordered table-responsive table-hover">
            <thead>
                <tr>
                    <th>Film</th>
                    <th>Title</th>
                    <th>Length in minutes</th>
                    <th>Director of  movie</th>
                    <th>Average Rating</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Film movie in Model)
                {
                    <tr onclick="location.href='@(Url.Action("ShowMovieDetails", "Movies", new {Id = movie.FilmId, Title = movie.Title, Length = movie.Length, ReleaseDate = movie.ReleaseDate }))'">
                        <td>@movie.FilmId</td>
                        <td>@movie.Title</td>
                        <td>@movie.Length</td>
                        <td>@movie.Director</td>
                        <td>@movie.AverageRate</td>
                        <td>@Html.ActionLink("Edit", "Edit", new { id = movie.FilmId })  | @Html.ActionLink("Rate movie", "RateMovie", new { id = movie.FilmId }) </td>

                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Views/Movies/ListAllMoviesForGenre.cshtml
@model MovieDatabase.ViewModels.GenreAndMoviesViewModel
@{
    ViewData["Title"] = "ListAllMoviesForGenre";
}

<h1>ListAllMoviesForGenre</h1>
<p>
    @(String.Format("{0} {1}",  "Genre", Model.MovieGenrie.Name))
</p>
<p>All movies in this genre all listed below</p>
<table class="table table-bordered table-responsive table-hover">
    <thead>
        <tr>
            <th>Title</th>
            <th>Length</th>
            <th>Release date</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var movie in Model.Movies)
    {
        <tr>
            <td>@movie.Title</td>
            <td>@movie.Length</td>
            <td>@movie.ReleaseDate</td>
        </tr>
    }
    </tbody>

</table>

Views/Movies/ListAllMoviesForRole.cshtml
@model MovieDatabase.ViewModels.RoleAndMoviesViewModel

@{bool isActor = false; }
@{ bool isDirector = false;}
@if (Model.MovieRole.GetType() == typeof(Star))
{
    isActor = true;
}
@if (Model.MovieRole.GetType() == typeof(Director))
{
    isDirector = true;
}

@if (isActor)
{
    ViewData["Title"] = "List all movie for star";
    <h1>List all star for actor</h1>
    @(String.Format("{0} {1}, {2}, {3} ",  "Director", Model.MovieRole.FirstName, " ",  Model.MovieRole.LastName))
}
@if (isDirector)
{
    ViewData["Title"] = "List all moview for director";

    <h1>List all movie for director</h1>
    @(String.Format("{0} {1}, {2}, {3} ",  "Director", Model.MovieRole.FirstName, " ",  Model.MovieRole.LastName))
}


<p>

</p>
<table class="table table-bordered table-responsive table-hover">

    <tr>
        <th>Title</th>
        <th>Length</th>
        <th>Release date</th>
    </tr>

    @foreach (var movie in Model.Movies)
    {
        <tr>
            <td>@movie.Title</td>
            <td>@movie.Length</td>
            <td>@movie.ReleaseDate</td>
        </tr>
    }
</table>

Views/Movies/MoviesAndTvShown.cshtml
@model MovieDatabase.ViewModels.FilmViewModel
@{
    ViewData["Title"] = "MoviesAndTvShown";
}

<h1>Movies And TvShown</h1>

<h1>Movies</h1>
<div class="panel-body">
    <table class="table table-bordered table-responsive table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Length</th>
                <th>Director</th>
                <th>Rating</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (Movie movie in Model.Movies)
            {
                <tr>
                    <td>@movie.FilmId</td>
                    <td>@movie.Title</td>
                    <td>@movie.Length</td>
                    <td>@movie.Director</td>
                    <td>@movie.Rating</td>
                    <td>@Html.ActionLink("Show movie details", "ShowMovieDetails",  new { Id = movie.FilmId }) |  @Html.ActionLink("Edit", "Edit", new { id = movie.FilmId })  | @Html.ActionLink("Rate movie", "RateFilm", new { id = movie.FilmId }) </td>

                </tr>
            }
        </tbody>
    </table>

</div>
<h1>TvShown</h1>
<div class="panel-body">
    <table class="table table-bordered table-responsive table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Length</th>
                <th>Director</th>
                <th>Rating</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (TvShow movie in Model.TvShows)
            {
                <tr >
                    <td>@movie.FilmId</td>
                    <td>@movie.Title</td>
                    <td>@movie.Length</td>
                    <td>@movie.Director</td>
                    <td>@movie.Rating</td>
                    <td>@Html.ActionLink("Show movie details", "ShowMovieDetails", "TvShow", new { Id = movie.FilmId }) |  @Html.ActionLink("Edit", "Edit", "TvShow", new { id = movie.FilmId })  | @Html.ActionLink("Rate movie", "RateFilm", new { id = movie.FilmId })  </td>

                </tr>
            }
        </tbody>
    </table>
</div>

Views/Movies/RateFilm.cshtml
@model MovieDatabase.Models.Film
@{
    //ViewData["Title"] = "Rate Movie or Tv show"; set
    // set layout to null
}
    <form asp-action="SubmitRating" method="post">
        <input type="hidden" asp-for="FilmId" />
        <p>
            @Html.TextBox("Title", null, new { @class = "form-control", @readonly = "readonly" })
        </p>
        <p>
            @Html.TextBox("ReleaseDate", null, new { @class = "form-control", @readonly = "readonly" })
        </p>
        <p>

        </p>
        <p>
            <label asp-for="Rating">Rate the movie</label>
            <input type="number" id="Rating" name="Rating" value="" />
        </p>
        <br />
        <button type="submit">Submit your rating</button>
    </form>